root: true
extends:
  - eslint:recommended
  - airbnb-base
  - airbnb-typescript/base
parser: "@typescript-eslint/parser"
parserOptions:
  project:
    - "./tsconfig.json"
    - './packages/*/tsconfig.json'
plugins:
  - "@typescript-eslint"
  - import
settings:
  "import/resolver":
    node:
      extensions:
        - ".ts"
rules:
  import/prefer-default-export: 0
  implicit-arrow-linebreak: 0
  import/extensions:
    - error
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never
  semi: [error, never]
  "@typescript-eslint/semi": [error, never]
  function-paren-newline: [error, consistent]
  object-curly-newline: [error, { consistent: true }]
  operator-linebreak: [error, after, { overrides: {
    '?': before,
    ':': before,
    '||': before,
    '&&': before
    }}]
