name: Auto AWS Lambda deployment
on:
  push:
    branches:
      - main
jobs:
  Depencency install:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: install depsendencies
      run: npm ci
  Build:
    steps:
    - name: Build lambda
      run: npm run build
    - name: Zip lambda function
      run: npm run postbuild
    - name: Install aws-cli
      run: sudo snap install aws-cli --classic
  Deploy:
    steps:
    - name: Deploy Production
      id: deployproduction
      run: npm run deploy:production
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
        AWS_REGION: us-east-1
  Update:
    steps:
    - name: Update code of deployed function
      if: failure()
      run: npm run deploy:production:update
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
        AWS_REGION: us-east-1

      
