name: Auto AWS Lambda deployment
on:
  push:
    branches:
      - main
jobs:
  auto-deploy-lambda:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: install depsendencies
      run: npm ci
    - name: Build lambda
      run: npm run build
      
