name: Auto AWS Lambda deployment
on:
  push:
    branches:
      - main
jobs:
  auto-deploy-lambda:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: install depsendencies
      run: npm ci
    - name: Build lambda
      run: npm run build
    - name: Zip lambda function
      run: npm run postbuild
    - name: Install aws-cli
      run: sudo snap install aws-cli --classic
    - name: Deploy Production
      id: deployproduction
      run: npm run deploy:production
      continue-on-error: true
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
        AWS_REGION: us-east-1
    - name: Update code of deployed function
      if: failure() && steps.deployproduction.outcome == 'failure'
      run: npm run deploy:production:update
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
        AWS_REGION: us-east-1

      
